#spring:
#  datasource:
#    url: jdbc:mysql:file:/data/demo
#    username: sa
#    password: password
#    driverClassName: org.h2.Driver
#  jpa:
#    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
#  sql:
#    init:
#      mode: always
spring:
    sql:
      init:
        mode: never